# Generated by Django 5.1.5 on 2025-01-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLib', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.AlterField(
            model_name='bookborrowing',
            name='borrow_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookborrowing',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookborrowing',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
